apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "careerhub.name" . }}-config
  namespace: {{ include "careerhub.namespace" . }}
  labels:
    {{- include "careerhub.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.backend.service.port | quote }}
  DB_HOST: {{ include "careerhub.name" . }}-postgres
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgres.database | quote }}
  JWT_EXPIRATION: {{ .Values.config.jwtExpiration | quote }}
  FILE_STORAGE_PATH: {{ .Values.config.fileStoragePath | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
  API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
  SEED_DEMO_DATA: {{ .Values.config.seedDemoData | quote }}
