apiVersion: v1
kind: Secret
metadata:
  name: {{ include "careerhub.name" . }}-secrets
  namespace: {{ include "careerhub.namespace" . }}
  labels:
    {{- include "careerhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
