apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: careerhub-postgres-data
  namespace: careerhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: careerhub-backend-storage
  namespace: careerhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
