package com.careerhub.notification;

public enum NotificationType {
    COMPANY_APPROVED,
    COMPANY_REJECTED,
    COMPANY_SUSPENDED,
    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,
    CERTIFICATE_VERIFIED,
    CERTIFICATE_REJECTED,
    ASSESSMENT_RESULT,
    ANNOUNCEMENT
}
